[package]
name = "tra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["error"]

error = ["warn"]
warn = ["debug"]
debug = ["info"]
info = []